name = "xtc-rtos-app-install"
main = "src/index.js"
compatibility_date = "2026-09-12"

# KV：替代 R2，存 manifest + rpk + 图标 + 元数据
[[kv_namespaces]]
binding = "STORE"
id = "在这里填新建STORE命名空间的真实id"
preview_id = "可选，preview命名空间id"

# 审计日志 KV
[[kv_namespaces]]
binding = "AUDIT"
id = "708ce2c0cdd7454cb1c1c1a78169d43b"
preview_id = "43ee37418b1847dfa25aef606695a764"

[vars]
MANIFEST_SECRET = "dev-secret-change-me"
